name: 'Changelog'
on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Verify repository
        run: ls -la

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          body: ${{steps.github_release.outputs.changelog}}

      - name: Update changelog
        run: |
          echo "## New Changes\n" >> changelog.md
          echo ${{ steps.github_release.outputs.changelog }}
          echo "${{ steps.github_release.outputs.changelog }}\n" >> changelog.md

      # Configure git
      - name: Configure Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Commit and push changes
      - name: Commit and push changes
        run: |
          git fetch origin
          git checkout master
          git add changelog.md
          git commit -m "Update changelog"
          git push origin HEAD:master
        env:
          # Set the environment variable GITHUB_TOKEN to use the GitHub Actions token for authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}