name: 'CHangelog'
on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Verify tag is from master
        id: check_master
        run: |
          # Fetch the master branch
          git fetch origin master:master
          # Check if the tag is on the master branch
          if git merge-base --is-ancestor master HEAD; then
            echo "is_master=true" >> $GITHUB_ENV
          else
            echo "is_master=false" >> $GITHUB_ENV

      - name: Exit if not from master
        if: env.is_master == 'false'
        run: exit 0

      - name: Verify repository
        run: ls -la

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          body: ${{steps.github_release.outputs.changelog}}

      # Append or create content for changelog.md
      - name: Update changelog
        run: |
          echo "## New Changes\n" >> changelog.md
          echo "Describe the new changes here." >> changelog.md

      # Configure git
      - name: Configure Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: pwd
        run: pwd

      - name: ls files
        run: ls

      # Verify Git status
      - name: Verify Git status
        run: git status
        env:
          # Set the environment variable GITHUB_TOKEN to use the GitHub Actions token for authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Commit and push changes
      - name: Commit and push changes
        run: |
          git fetch origin
          git checkout master
          git add changelog.md
          git commit -m "Update changelog"
          git push origin HEAD:master
        env:
          # Set the environment variable GITHUB_TOKEN to use the GitHub Actions token for authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}